# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request] # Run on Push and Pull Requests

jobs:
  build:
    name: TestAsb
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: flow # will run `flow` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: goosebuild # will run `yarn goosebuild` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: goosetest # will run `yarn goosetest` command
